import type { GeneratedRecipe } from '../server/utils/anthropic'

// Третий батч. Те же правила (калорийные ингредиенты, name_en для USDA).
export const RECIPES_3: GeneratedRecipe[] = [
  {
    title: 'Лобио',
    description: 'Грузинское рагу из красной фасоли с орехами.',
    cuisine: 'georgian',
    category: 'main',
    base_servings: 2,
    time_minutes: 30,
    ingredients: [
      { name: 'Красная фасоль', name_en: 'beans, kidney, canned', grams: 250, display_text: '1 банка', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Грецкие орехи', name_en: 'walnuts', grams: 50, display_text: '50 г', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Обжарьте лук на масле.',
      'Добавьте фасоль, разомните часть, прогрейте.',
      'Вмешайте молотые орехи и специи (кинза, хмели-сунели), посолите.',
    ],
  },
  {
    title: 'Чахохбили',
    description: 'Грузинское рагу из курицы в томатах.',
    cuisine: 'georgian',
    category: 'main',
    base_servings: 2,
    time_minutes: 50,
    ingredients: [
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 350, display_text: '2–3 шт.', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 250, display_text: '3 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Обжарьте курицу до румяности.',
      'Добавьте лук, затем тёртые томаты.',
      'Тушите 25 минут, добавьте зелень и специи, посолите.',
    ],
  },
  {
    title: 'Хачапури',
    description: 'Грузинская лепёшка с сыром.',
    cuisine: 'georgian',
    category: 'snack',
    base_servings: 2,
    time_minutes: 60,
    ingredients: [
      { name: 'Мука', name_en: 'wheat flour', grams: 200, display_text: '1.5 стакана', is_optional: false },
      { name: 'Сыр', name_en: 'mozzarella cheese', grams: 200, display_text: '200 г', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 50, display_text: '1 шт.', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 30, display_text: '30 г', is_optional: false },
    ],
    steps: [
      'Замесите тесто из муки, воды и щепотки соли, дайте отдохнуть.',
      'Заверните тёртый сыр в тесто, раскатайте лепёшкой.',
      'Выпекайте, смажьте маслом, вбейте яйцо за пару минут до готовности.',
    ],
  },
  {
    title: 'Аджапсандали',
    description: 'Грузинское овощное рагу.',
    cuisine: 'georgian',
    category: 'side',
    base_servings: 2,
    time_minutes: 40,
    ingredients: [
      { name: 'Баклажан', name_en: 'eggplant, raw', grams: 200, display_text: '1 шт.', is_optional: false },
      { name: 'Болгарский перец', name_en: 'bell pepper, raw', grams: 120, display_text: '1 шт.', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 150, display_text: '2 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 25, display_text: '2 ст. л.', is_optional: false },
    ],
    steps: [
      'Обжарьте лук и перец.',
      'Добавьте баклажаны и томаты, тушите 20 минут.',
      'Добавьте чеснок и зелень, посолите.',
    ],
  },
  {
    title: 'Курица терияки',
    description: 'Японская курица в сладко-солёном соусе.',
    cuisine: 'japanese',
    category: 'main',
    base_servings: 2,
    time_minutes: 30,
    ingredients: [
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 300, display_text: '2 шт.', is_optional: false },
      { name: 'Соевый соус', name_en: 'soy sauce', grams: 40, display_text: '3 ст. л.', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 20, display_text: '1 ст. л.', is_optional: false },
      { name: 'Мёд', name_en: 'honey', grams: 20, display_text: '1 ст. л.', is_optional: false },
      { name: 'Рис', name_en: 'rice, white, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
    ],
    steps: [
      'Обжарьте курицу до румяности.',
      'Влейте соус из сои, сахара и мёда, выпарите до глянца.',
      'Подавайте с отварным рисом.',
    ],
  },
  {
    title: 'Якисоба',
    description: 'Японская жареная лапша со свининой.',
    cuisine: 'japanese',
    category: 'main',
    base_servings: 2,
    time_minutes: 25,
    ingredients: [
      { name: 'Лапша', name_en: 'egg noodles, dry', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Свинина', name_en: 'pork, raw', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Капуста', name_en: 'cabbage, raw', grams: 150, display_text: '1/4 кочана', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 70, display_text: '1 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
      { name: 'Соевый соус', name_en: 'soy sauce', grams: 30, display_text: '2 ст. л.', is_optional: false },
    ],
    steps: [
      'Отварите лапшу. Обжарьте свинину полосками.',
      'Добавьте капусту и морковь, обжарьте.',
      'Вмешайте лапшу и соевый соус, прогрейте.',
    ],
  },
  {
    title: 'Лосось терияки',
    description: 'Запечённый лосось в соусе терияки с рисом.',
    cuisine: 'japanese',
    category: 'main',
    base_servings: 2,
    time_minutes: 25,
    ingredients: [
      { name: 'Лосось', name_en: 'salmon, raw', grams: 300, display_text: '2 стейка', is_optional: false },
      { name: 'Соевый соус', name_en: 'soy sauce', grams: 30, display_text: '2 ст. л.', is_optional: false },
      { name: 'Мёд', name_en: 'honey', grams: 20, display_text: '1 ст. л.', is_optional: false },
      { name: 'Рис', name_en: 'rice, white, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
    ],
    steps: [
      'Замаринуйте лосось в сое с мёдом 10 минут.',
      'Обжарьте или запеките до готовности, полейте загущённым соусом.',
      'Подавайте с рисом.',
    ],
  },
  {
    title: 'Лазанья',
    description: 'Слоёная паста с мясным соусом и сыром.',
    cuisine: 'italian',
    category: 'main',
    base_servings: 2,
    time_minutes: 70,
    ingredients: [
      { name: 'Листы лазаньи', name_en: 'pasta, dry', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Говяжий фарш', name_en: 'ground beef, raw', grams: 250, display_text: '250 г', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 250, display_text: '3 шт.', is_optional: false },
      { name: 'Моцарелла', name_en: 'mozzarella cheese', grams: 100, display_text: '100 г', is_optional: false },
      { name: 'Пармезан', name_en: 'parmesan cheese', grams: 30, display_text: '30 г', is_optional: false },
    ],
    steps: [
      'Приготовьте мясной соус с томатами.',
      'Выложите слоями листы, соус и сыр.',
      'Запекайте при 180 °C около 35 минут.',
    ],
  },
  {
    title: 'Паста песто',
    description: 'Паста с соусом песто и кедровыми орехами.',
    cuisine: 'italian',
    category: 'main',
    base_servings: 2,
    time_minutes: 20,
    ingredients: [
      { name: 'Паста', name_en: 'pasta, dry', grams: 200, display_text: '200 г', is_optional: false },
      { name: 'Базилик', name_en: 'basil, fresh', grams: 30, display_text: '1 пучок', is_optional: false },
      { name: 'Кедровые орехи', name_en: 'pine nuts', grams: 30, display_text: '30 г', is_optional: false },
      { name: 'Пармезан', name_en: 'parmesan cheese', grams: 30, display_text: '30 г', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 30, display_text: '2 ст. л.', is_optional: false },
      { name: 'Чеснок', name_en: 'garlic, raw', grams: 10, display_text: '2 зубчика', is_optional: false },
    ],
    steps: [
      'Отварите пасту.',
      'Измельчите базилик, орехи, чеснок, пармезан и масло в песто.',
      'Смешайте пасту с песто.',
    ],
  },
  {
    title: 'Табуле',
    description: 'Левантийский салат с булгуром и зеленью.',
    cuisine: 'mediterranean',
    category: 'salad',
    base_servings: 2,
    time_minutes: 25,
    ingredients: [
      { name: 'Булгур', name_en: 'bulgur, dry', grams: 100, display_text: '1/2 стакана', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 60, display_text: '1/2 шт.', is_optional: false },
      { name: 'Петрушка', name_en: 'parsley, fresh', grams: 40, display_text: '1 пучок', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Запарьте булгур кипятком до мягкости.',
      'Смешайте с нарезанными томатами, луком и петрушкой.',
      'Заправьте маслом и лимонным соком, посолите.',
    ],
  },
  {
    title: 'Фалафель',
    description: 'Жареные шарики из нута.',
    cuisine: 'mediterranean',
    category: 'snack',
    base_servings: 2,
    time_minutes: 35,
    ingredients: [
      { name: 'Нут', name_en: 'chickpeas, canned', grams: 250, display_text: '1 банка', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Чеснок', name_en: 'garlic, raw', grams: 10, display_text: '2 зубчика', is_optional: false },
      { name: 'Мука', name_en: 'wheat flour', grams: 40, display_text: '3 ст. л.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 30, display_text: 'для жарки', is_optional: false },
    ],
    steps: [
      'Измельчите нут с луком, чесноком и специями.',
      'Добавьте муку, сформируйте шарики.',
      'Обжарьте во фритюре до золотистой корочки.',
    ],
  },
  {
    title: 'Тако с говядиной',
    description: 'Мексиканские тортильи с мясом и сыром.',
    cuisine: 'mexican',
    category: 'main',
    base_servings: 2,
    time_minutes: 25,
    ingredients: [
      { name: 'Тортилья', name_en: 'tortilla, flour', grams: 120, display_text: '3 шт.', is_optional: false },
      { name: 'Говяжий фарш', name_en: 'ground beef, raw', grams: 250, display_text: '250 г', is_optional: false },
      { name: 'Сыр чеддер', name_en: 'cheddar cheese', grams: 80, display_text: '80 г', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 60, display_text: '1/2 шт.', is_optional: false },
    ],
    steps: [
      'Обжарьте фарш с луком и специями.',
      'Прогрейте тортильи.',
      'Наполните мясом, томатами и тёртым сыром.',
    ],
  },
  {
    title: 'Буррито с курицей',
    description: 'Сытный ролл с рисом, фасолью и курицей.',
    cuisine: 'mexican',
    category: 'main',
    base_servings: 2,
    time_minutes: 30,
    ingredients: [
      { name: 'Тортилья', name_en: 'tortilla, flour', grams: 120, display_text: '2 больших', is_optional: false },
      { name: 'Рис', name_en: 'rice, white, raw', grams: 80, display_text: '80 г', is_optional: false },
      { name: 'Красная фасоль', name_en: 'beans, kidney, canned', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 150, display_text: '1 шт.', is_optional: false },
      { name: 'Сыр чеддер', name_en: 'cheddar cheese', grams: 80, display_text: '80 г', is_optional: false },
    ],
    steps: [
      'Отварите рис, обжарьте курицу.',
      'На тортилью выложите рис, фасоль, курицу и сыр.',
      'Заверните рулетом и обжарьте на сухой сковороде.',
    ],
  },
  {
    title: 'Начос',
    description: 'Чипсы с расплавленным сыром и фасолью.',
    cuisine: 'mexican',
    category: 'snack',
    base_servings: 2,
    time_minutes: 15,
    ingredients: [
      { name: 'Кукурузные чипсы', name_en: 'tortilla chips', grams: 100, display_text: '100 г', is_optional: false },
      { name: 'Сыр чеддер', name_en: 'cheddar cheese', grams: 80, display_text: '80 г', is_optional: false },
      { name: 'Красная фасоль', name_en: 'beans, kidney, canned', grams: 100, display_text: '100 г', is_optional: false },
    ],
    steps: [
      'Выложите чипсы на противень.',
      'Посыпьте сыром и фасолью.',
      'Запекайте 5–7 минут до плавления сыра.',
    ],
  },
  {
    title: 'Луковый суп',
    description: 'Французский суп с карамелизованным луком и сыром.',
    cuisine: 'french',
    category: 'soup',
    base_servings: 2,
    time_minutes: 50,
    ingredients: [
      { name: 'Лук', name_en: 'onion, raw', grams: 400, display_text: '4 шт.', is_optional: false },
      { name: 'Хлеб', name_en: 'bread, white', grams: 80, display_text: '2 ломтика', is_optional: false },
      { name: 'Сыр', name_en: 'swiss cheese', grams: 80, display_text: '80 г', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 30, display_text: '30 г', is_optional: false },
    ],
    steps: [
      'Карамелизуйте лук на масле 25 минут.',
      'Залейте бульоном, варите 15 минут.',
      'Разлейте, сверху положите хлеб и сыр, запеките до корочки.',
    ],
  },
  {
    title: 'Крок-месье',
    description: 'Горячий французский сэндвич с ветчиной и сыром.',
    cuisine: 'french',
    category: 'snack',
    base_servings: 2,
    time_minutes: 20,
    ingredients: [
      { name: 'Хлеб', name_en: 'bread, white', grams: 150, display_text: '4 ломтика', is_optional: false },
      { name: 'Ветчина', name_en: 'ham, sliced', grams: 100, display_text: '100 г', is_optional: false },
      { name: 'Сыр', name_en: 'swiss cheese', grams: 80, display_text: '80 г', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 20, display_text: '20 г', is_optional: false },
    ],
    steps: [
      'Соберите сэндвичи с ветчиной и сыром.',
      'Смажьте маслом, обжарьте с двух сторон.',
      'Сверху добавьте сыр и подрумяньте.',
    ],
  },
  {
    title: 'Картофельный гратен',
    description: 'Запечённый картофель в сливках с сыром.',
    cuisine: 'french',
    category: 'side',
    base_servings: 2,
    time_minutes: 60,
    ingredients: [
      { name: 'Картофель', name_en: 'potato, raw', grams: 500, display_text: '5 шт.', is_optional: false },
      { name: 'Молоко', name_en: 'milk, 3.25% milkfat', grams: 150, display_text: '3/4 стакана', is_optional: false },
      { name: 'Сыр грюйер', name_en: 'gruyere cheese', grams: 100, display_text: '100 г', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 20, display_text: '20 г', is_optional: false },
    ],
    steps: [
      'Нарежьте картофель тонкими кружочками.',
      'Выложите в форму, залейте молоком, посыпьте сыром.',
      'Запекайте при 180 °C около 45 минут.',
    ],
  },
  {
    title: 'Палак панир',
    description: 'Индийский шпинат с творожным сыром.',
    cuisine: 'indian',
    category: 'side',
    base_servings: 2,
    time_minutes: 30,
    ingredients: [
      { name: 'Шпинат', name_en: 'spinach, raw', grams: 300, display_text: '300 г', is_optional: false },
      { name: 'Сыр (панир)', name_en: 'ricotta cheese', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 60, display_text: '1/2 шт.', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 20, display_text: '20 г', is_optional: false },
    ],
    steps: [
      'Припустите и пробейте шпинат в пюре.',
      'Обжарьте лук со специями на масле, добавьте шпинат.',
      'Положите кубики сыра, прогрейте, посолите.',
    ],
  },
  {
    title: 'Жареный рис с яйцом',
    description: 'Быстрый жареный рис с овощами.',
    cuisine: 'thai',
    category: 'main',
    base_servings: 2,
    time_minutes: 20,
    ingredients: [
      { name: 'Рис', name_en: 'rice, white, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 100, display_text: '2 шт.', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 60, display_text: '1 шт.', is_optional: false },
      { name: 'Зелёный горошек', name_en: 'peas, green, raw', grams: 60, display_text: '60 г', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
      { name: 'Соевый соус', name_en: 'soy sauce', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Отварите рис заранее и остудите.',
      'Обжарьте овощи, отодвиньте, поджарьте яйца.',
      'Добавьте рис и соевый соус, прогрейте, помешивая.',
    ],
  },
  {
    title: 'Рисовый пудинг',
    description: 'Молочная рисовая каша-десерт с изюмом.',
    cuisine: 'russian',
    category: 'dessert',
    base_servings: 2,
    time_minutes: 35,
    ingredients: [
      { name: 'Рис', name_en: 'rice, white, raw', grams: 100, display_text: '1/2 стакана', is_optional: false },
      { name: 'Молоко', name_en: 'milk, 3.25% milkfat', grams: 400, display_text: '2 стакана', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 40, display_text: '2 ст. л.', is_optional: false },
      { name: 'Изюм', name_en: 'raisins', grams: 30, display_text: '30 г', is_optional: true },
    ],
    steps: [
      'Отварите рис до полуготовности.',
      'Влейте молоко с сахаром, варите на слабом огне до густоты.',
      'Добавьте изюм, дайте настояться.',
    ],
  },
  {
    title: 'Овсяное печенье',
    description: 'Домашнее печенье из овсяных хлопьев.',
    cuisine: 'russian',
    category: 'dessert',
    base_servings: 2,
    time_minutes: 30,
    ingredients: [
      { name: 'Овсяные хлопья', name_en: 'cereals, oats, regular', grams: 120, display_text: '120 г', is_optional: false },
      { name: 'Мука', name_en: 'wheat flour', grams: 80, display_text: '1/2 стакана', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 60, display_text: '60 г', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 60, display_text: '3 ст. л.', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 50, display_text: '1 шт.', is_optional: false },
    ],
    steps: [
      'Смешайте все ингредиенты в тесто.',
      'Сформируйте печенья на противне.',
      'Выпекайте при 180 °C 15 минут.',
    ],
  },
  {
    title: 'Молочный коктейль с бананом',
    description: 'Освежающий банановый шейк.',
    cuisine: 'russian',
    category: 'drink',
    base_servings: 2,
    time_minutes: 5,
    ingredients: [
      { name: 'Молоко', name_en: 'milk, 3.25% milkfat', grams: 400, display_text: '2 стакана', is_optional: false },
      { name: 'Банан', name_en: 'banana, raw', grams: 240, display_text: '2 шт.', is_optional: false },
      { name: 'Мёд', name_en: 'honey', grams: 30, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Сложите бананы, молоко и мёд в блендер.',
      'Взбейте до однородности, подавайте охлаждённым.',
    ],
  },
  {
    title: 'Овощи на гриле',
    description: 'Лёгкий гарнир из печёных овощей.',
    cuisine: 'mediterranean',
    category: 'side',
    base_servings: 2,
    time_minutes: 25,
    ingredients: [
      { name: 'Кабачок', name_en: 'zucchini, raw', grams: 200, display_text: '1 шт.', is_optional: false },
      { name: 'Болгарский перец', name_en: 'bell pepper, raw', grams: 150, display_text: '1–2 шт.', is_optional: false },
      { name: 'Баклажан', name_en: 'eggplant, raw', grams: 150, display_text: '1 шт.', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 25, display_text: '2 ст. л.', is_optional: false },
    ],
    steps: [
      'Нарежьте овощи крупными ломтиками.',
      'Сбрызните маслом, посолите.',
      'Обжарьте на гриль-сковороде до мягкости и полос.',
    ],
  },
]
