import type { GeneratedRecipe } from '../server/utils/anthropic'

// Четвёртый батч.
export const RECIPES_4: GeneratedRecipe[] = [
  {
    title: 'Голубцы',
    description: 'Капустные рулетики с мясом и рисом в томате.',
    cuisine: 'russian', category: 'main', base_servings: 2, time_minutes: 80,
    ingredients: [
      { name: 'Капуста', name_en: 'cabbage, raw', grams: 250, display_text: '1/2 кочана', is_optional: false },
      { name: 'Говяжий фарш', name_en: 'ground beef, raw', grams: 200, display_text: '200 г', is_optional: false },
      { name: 'Рис', name_en: 'rice, white, raw', grams: 60, display_text: '60 г', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 70, display_text: '1 шт.', is_optional: false },
      { name: 'Томатная паста', name_en: 'tomato paste', grams: 30, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: ['Отварите капустные листья до мягкости.', 'Смешайте фарш с полуготовым рисом и луком, заверните в листья.', 'Тушите в томатном соусе с морковью 40 минут.'],
  },
  {
    title: 'Котлеты',
    description: 'Домашние мясные котлеты.',
    cuisine: 'russian', category: 'main', base_servings: 2, time_minutes: 35,
    ingredients: [
      { name: 'Говяжий фарш', name_en: 'ground beef, raw', grams: 300, display_text: '300 г', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 60, display_text: '1 шт.', is_optional: false },
      { name: 'Хлеб', name_en: 'bread, white', grams: 40, display_text: '1 ломтик', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 50, display_text: '1 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: 'для жарки', is_optional: false },
    ],
    steps: ['Смешайте фарш с замоченным хлебом, луком и яйцом.', 'Сформируйте котлеты.', 'Обжарьте с двух сторон до готовности.'],
  },
  {
    title: 'Щи',
    description: 'Капустный суп на говядине.',
    cuisine: 'russian', category: 'soup', base_servings: 2, time_minutes: 80,
    ingredients: [
      { name: 'Говядина', name_en: 'beef, raw', grams: 200, display_text: '200 г', is_optional: false },
      { name: 'Капуста', name_en: 'cabbage, raw', grams: 200, display_text: '1/4 кочана', is_optional: false },
      { name: 'Картофель', name_en: 'potato, raw', grams: 150, display_text: '2 шт.', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 70, display_text: '1 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 70, display_text: '1 шт.', is_optional: false },
      { name: 'Томатная паста', name_en: 'tomato paste', grams: 20, display_text: '1 ст. л.', is_optional: false },
    ],
    steps: ['Сварите бульон, добавьте картофель и капусту.', 'Добавьте зажарку из лука, моркови и томатной пасты.', 'Варите до готовности, посолите.'],
  },
  {
    title: 'Окрошка',
    description: 'Холодный летний суп на кефире.',
    cuisine: 'russian', category: 'soup', base_servings: 2, time_minutes: 20,
    ingredients: [
      { name: 'Кефир', name_en: 'kefir', grams: 400, display_text: '2 стакана', is_optional: false },
      { name: 'Картофель', name_en: 'potato, raw', grams: 150, display_text: '2 шт.', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 100, display_text: '2 шт.', is_optional: false },
      { name: 'Огурцы', name_en: 'cucumber, raw', grams: 150, display_text: '1–2 шт.', is_optional: false },
      { name: 'Ветчина', name_en: 'ham, sliced', grams: 100, display_text: '100 г', is_optional: false },
    ],
    steps: ['Отварите картофель и яйца, остудите, нарежьте кубиками.', 'Добавьте огурцы и ветчину.', 'Залейте кефиром, посолите, добавьте зелень.'],
  },
  {
    title: 'Драники',
    description: 'Картофельные оладьи.',
    cuisine: 'russian', category: 'side', base_servings: 2, time_minutes: 30,
    ingredients: [
      { name: 'Картофель', name_en: 'potato, raw', grams: 400, display_text: '4 шт.', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 50, display_text: '1 шт.', is_optional: false },
      { name: 'Мука', name_en: 'wheat flour', grams: 40, display_text: '3 ст. л.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 30, display_text: 'для жарки', is_optional: false },
    ],
    steps: ['Натрите картофель, отожмите.', 'Смешайте с яйцом и мукой, посолите.', 'Жарьте оладьи на масле до румяности.'],
  },
  {
    title: 'Манная каша',
    description: 'Гладкая молочная каша на завтрак.',
    cuisine: 'russian', category: 'breakfast', base_servings: 2, time_minutes: 15,
    ingredients: [
      { name: 'Манная крупа', name_en: 'semolina', grams: 60, display_text: '4 ст. л.', is_optional: false },
      { name: 'Молоко', name_en: 'milk, 3.25% milkfat', grams: 300, display_text: '1.5 стакана', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 20, display_text: '1 ст. л.', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 15, display_text: '15 г', is_optional: false },
    ],
    steps: ['Доведите молоко до кипения.', 'Тонкой струйкой всыпьте манку, помешивая.', 'Варите 3 минуты, добавьте сахар и масло.'],
  },
  {
    title: 'Гороховый суп',
    description: 'Густой суп из колотого гороха.',
    cuisine: 'russian', category: 'soup', base_servings: 2, time_minutes: 70,
    ingredients: [
      { name: 'Горох', name_en: 'peas, split, mature, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 70, display_text: '1 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 70, display_text: '1 шт.', is_optional: false },
      { name: 'Картофель', name_en: 'potato, raw', grams: 150, display_text: '2 шт.', is_optional: false },
    ],
    steps: ['Отварите горох до мягкости (около 40 минут).', 'Добавьте картофель и зажарку из лука и моркови.', 'Варите до готовности, посолите.'],
  },
  {
    title: 'Запечённая курица с картофелем',
    description: 'Курица с картошкой в духовке.',
    cuisine: 'russian', category: 'main', base_servings: 2, time_minutes: 60,
    ingredients: [
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 300, display_text: '2 шт.', is_optional: false },
      { name: 'Картофель', name_en: 'potato, raw', grams: 300, display_text: '3 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: ['Нарежьте картофель и лук, выложите в форму.', 'Сверху — курицу, сбрызните маслом, посолите.', 'Запекайте при 200 °C 40 минут.'],
  },
  {
    title: 'Пицца Маргарита',
    description: 'Классическая пицца с томатами и моцареллой.',
    cuisine: 'italian', category: 'main', base_servings: 2, time_minutes: 50,
    ingredients: [
      { name: 'Мука', name_en: 'wheat flour', grams: 200, display_text: '1.5 стакана', is_optional: false },
      { name: 'Моцарелла', name_en: 'mozzarella cheese', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 150, display_text: '2 шт.', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: ['Замесите тесто, дайте подойти.', 'Раскатайте, выложите томаты и моцареллу.', 'Выпекайте при 230 °C 12 минут.'],
  },
  {
    title: 'Паста аррабиата',
    description: 'Острая паста в томатном соусе.',
    cuisine: 'italian', category: 'main', base_servings: 2, time_minutes: 25,
    ingredients: [
      { name: 'Паста', name_en: 'pasta, dry', grams: 200, display_text: '200 г', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 250, display_text: '3 шт.', is_optional: false },
      { name: 'Чеснок', name_en: 'garlic, raw', grams: 10, display_text: '2 зубчика', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 25, display_text: '2 ст. л.', is_optional: false },
    ],
    steps: ['Отварите пасту.', 'Обжарьте чеснок с острым перцем, добавьте томаты.', 'Смешайте соус с пастой.'],
  },
  {
    title: 'Карбонара',
    description: 'Паста с яйцом, сыром и свининой.',
    cuisine: 'italian', category: 'main', base_servings: 2, time_minutes: 25,
    ingredients: [
      { name: 'Паста', name_en: 'pasta, dry', grams: 200, display_text: '200 г', is_optional: false },
      { name: 'Свинина', name_en: 'pork, raw', grams: 120, display_text: '120 г', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 100, display_text: '2 шт.', is_optional: false },
      { name: 'Пармезан', name_en: 'parmesan cheese', grams: 40, display_text: '40 г', is_optional: false },
    ],
    steps: ['Отварите пасту. Обжарьте нарезанную свинину.', 'Смешайте яйца с тёртым пармезаном.', 'Соедините горячую пасту с яичной смесью и свининой вне огня.'],
  },
  {
    title: 'Курица тикка масала',
    description: 'Курица в пряном томатно-сливочном соусе.',
    cuisine: 'indian', category: 'main', base_servings: 2, time_minutes: 45,
    ingredients: [
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 300, display_text: '2 шт.', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Йогурт', name_en: 'yogurt, plain', grams: 100, display_text: '100 г', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 20, display_text: '20 г', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Рис', name_en: 'rice, white, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
    ],
    steps: ['Замаринуйте курицу в йогурте со специями, обжарьте.', 'Добавьте лук и томаты, тушите 20 минут с маслом.', 'Подавайте с рисом.'],
  },
  {
    title: 'Чана масала',
    description: 'Индийское карри из нута.',
    cuisine: 'indian', category: 'main', base_servings: 2, time_minutes: 30,
    ingredients: [
      { name: 'Нут', name_en: 'chickpeas, canned', grams: 250, display_text: '1 банка', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
      { name: 'Рис', name_en: 'rice, white, raw', grams: 120, display_text: '120 г', is_optional: false },
    ],
    steps: ['Обжарьте лук со специями.', 'Добавьте томаты и нут, тушите 15 минут.', 'Подавайте с рисом.'],
  },
  {
    title: 'Бирьяни с курицей',
    description: 'Ароматный рис с курицей и специями.',
    cuisine: 'indian', category: 'main', base_servings: 2, time_minutes: 50,
    ingredients: [
      { name: 'Рис', name_en: 'rice, white, raw', grams: 180, display_text: '1 стакан', is_optional: false },
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 250, display_text: '2 шт.', is_optional: false },
      { name: 'Йогурт', name_en: 'yogurt, plain', grams: 80, display_text: '80 г', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: ['Замаринуйте курицу в йогурте со специями.', 'Обжарьте лук, добавьте курицу, затем рис и воду.', 'Готовьте под крышкой до впитывания воды.'],
  },
  {
    title: 'Токпокки',
    description: 'Корейские рисовые палочки в сладко-остром соусе.',
    cuisine: 'korean', category: 'main', base_servings: 2, time_minutes: 25,
    ingredients: [
      { name: 'Рисовые палочки', name_en: 'rice cakes', grams: 250, display_text: '250 г', is_optional: false },
      { name: 'Капуста', name_en: 'cabbage, raw', grams: 100, display_text: '100 г', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 60, display_text: '1 шт.', is_optional: false },
      { name: 'Соевый соус', name_en: 'soy sauce', grams: 30, display_text: '2 ст. л.', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 20, display_text: '1 ст. л.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 15, display_text: '1 ст. л.', is_optional: false },
    ],
    steps: ['Замочите рисовые палочки в горячей воде.', 'Обжарьте овощи, добавьте соус из сои, сахара и острого перца.', 'Добавьте палочки, тушите до загустения.'],
  },
  {
    title: 'Пулькоги',
    description: 'Корейская маринованная говядина.',
    cuisine: 'korean', category: 'main', base_servings: 2, time_minutes: 30,
    ingredients: [
      { name: 'Говядина', name_en: 'beef, raw', grams: 300, display_text: '300 г', is_optional: false },
      { name: 'Соевый соус', name_en: 'soy sauce', grams: 30, display_text: '2 ст. л.', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 15, display_text: '1 ст. л.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Кунжутное масло', name_en: 'sesame oil', grams: 15, display_text: '1 ст. л.', is_optional: false },
      { name: 'Рис', name_en: 'rice, white, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
    ],
    steps: ['Замаринуйте тонко нарезанную говядину в сое, сахаре и масле.', 'Обжарьте на сильном огне с луком.', 'Подавайте с рисом.'],
  },
  {
    title: 'Японское карри',
    description: 'Густое японское карри с курицей и овощами.',
    cuisine: 'japanese', category: 'main', base_servings: 2, time_minutes: 45,
    ingredients: [
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 250, display_text: '2 шт.', is_optional: false },
      { name: 'Картофель', name_en: 'potato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Рис', name_en: 'rice, white, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: ['Обжарьте курицу и овощи.', 'Залейте водой, добавьте карри-пасту, тушите до густоты.', 'Подавайте с рисом.'],
  },
  {
    title: 'Удон с курицей',
    description: 'Японский суп с лапшой удон.',
    cuisine: 'japanese', category: 'soup', base_servings: 2, time_minutes: 25,
    ingredients: [
      { name: 'Лапша удон', name_en: 'egg noodles, dry', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 150, display_text: '1 шт.', is_optional: false },
      { name: 'Соевый соус', name_en: 'soy sauce', grams: 30, display_text: '2 ст. л.', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 50, display_text: '1 шт.', is_optional: false },
      { name: 'Зелёный лук', name_en: 'scallions, raw', grams: 20, display_text: '2 пера', is_optional: false },
    ],
    steps: ['Сварите бульон с соевым соусом.', 'Отварите лапшу и курицу.', 'Соберите суп, добавьте яйцо и зелёный лук.'],
  },
  {
    title: 'Тамаго (японский омлет)',
    description: 'Сладковатый свёрнутый омлет.',
    cuisine: 'japanese', category: 'breakfast', base_servings: 2, time_minutes: 15,
    ingredients: [
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 200, display_text: '4 шт.', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 15, display_text: '1 ст. л.', is_optional: false },
      { name: 'Соевый соус', name_en: 'soy sauce', grams: 10, display_text: '1 ч. л.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 10, display_text: '1 ч. л.', is_optional: false },
    ],
    steps: ['Взбейте яйца с сахаром и соевым соусом.', 'Жарьте тонкими слоями, сворачивая в рулет.', 'Нарежьте ломтиками.'],
  },
  {
    title: 'Том кха гай',
    description: 'Тайский кокосовый суп с курицей.',
    cuisine: 'thai', category: 'soup', base_servings: 2, time_minutes: 30,
    ingredients: [
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 250, display_text: '2 шт.', is_optional: false },
      { name: 'Кокосовое молоко', name_en: 'coconut milk, canned', grams: 200, display_text: '1 стакан', is_optional: false },
      { name: 'Грибы', name_en: 'mushrooms, white, raw', grams: 100, display_text: '100 г', is_optional: false },
    ],
    steps: ['Доведите воду с кокосовым молоком до кипения.', 'Добавьте курицу и грибы, варите 15 минут.', 'Приправьте имбирём и лаймом по вкусу.'],
  },
  {
    title: 'Манго стики райс',
    description: 'Тайский десерт: клейкий рис с манго.',
    cuisine: 'thai', category: 'dessert', base_servings: 2, time_minutes: 40,
    ingredients: [
      { name: 'Рис', name_en: 'rice, white, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
      { name: 'Кокосовое молоко', name_en: 'coconut milk, canned', grams: 120, display_text: '1/2 стакана', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 40, display_text: '2 ст. л.', is_optional: false },
      { name: 'Манго', name_en: 'mango, raw', grams: 200, display_text: '1 шт.', is_optional: false },
    ],
    steps: ['Отварите рис.', 'Прогрейте кокосовое молоко с сахаром, смешайте с рисом.', 'Подавайте с нарезанным манго.'],
  },
  {
    title: 'Хумус',
    description: 'Нутовая паста с тахини.',
    cuisine: 'mediterranean', category: 'snack', base_servings: 2, time_minutes: 10,
    ingredients: [
      { name: 'Нут', name_en: 'chickpeas, canned', grams: 250, display_text: '1 банка', is_optional: false },
      { name: 'Тахини', name_en: 'sesame butter, tahini', grams: 40, display_text: '2 ст. л.', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
      { name: 'Чеснок', name_en: 'garlic, raw', grams: 10, display_text: '2 зубчика', is_optional: false },
    ],
    steps: ['Пробейте нут с тахини, чесноком и маслом в блендере.', 'Добавьте лимонный сок и воду до кремовости.', 'Посолите.'],
  },
  {
    title: 'Гирос с курицей',
    description: 'Греческая пита с курицей и соусом.',
    cuisine: 'mediterranean', category: 'main', base_servings: 2, time_minutes: 30,
    ingredients: [
      { name: 'Пита', name_en: 'pita bread', grams: 150, display_text: '2 шт.', is_optional: false },
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 200, display_text: '1 шт.', is_optional: false },
      { name: 'Йогурт', name_en: 'yogurt, plain', grams: 80, display_text: '80 г', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Огурцы', name_en: 'cucumber, raw', grams: 80, display_text: '1/2 шт.', is_optional: false },
    ],
    steps: ['Обжарьте курицу со специями.', 'Сделайте соус из йогурта и огурца.', 'Наполните питу курицей, томатами и соусом.'],
  },
  {
    title: 'Фахитас с курицей',
    description: 'Мексиканская курица с перцем в тортилье.',
    cuisine: 'mexican', category: 'main', base_servings: 2, time_minutes: 30,
    ingredients: [
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 250, display_text: '2 шт.', is_optional: false },
      { name: 'Болгарский перец', name_en: 'bell pepper, raw', grams: 150, display_text: '1–2 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Тортилья', name_en: 'tortilla, flour', grams: 120, display_text: '3 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: ['Нарежьте курицу и овощи полосками.', 'Обжарьте на сильном огне со специями.', 'Подавайте с тёплыми тортильями.'],
  },
  {
    title: 'Сальса',
    description: 'Мексиканский томатный соус-дип.',
    cuisine: 'mexican', category: 'snack', base_servings: 2, time_minutes: 10,
    ingredients: [
      { name: 'Томаты', name_en: 'tomato, raw', grams: 250, display_text: '3 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Чеснок', name_en: 'garlic, raw', grams: 10, display_text: '2 зубчика', is_optional: false },
    ],
    steps: ['Мелко нарежьте томаты, лук и чеснок.', 'Добавьте острый перец, кинзу и сок лайма.', 'Посолите, дайте настояться.'],
  },
  {
    title: 'Тарт татен',
    description: 'Французский яблочный пирог-перевёртыш.',
    cuisine: 'french', category: 'dessert', base_servings: 2, time_minutes: 55,
    ingredients: [
      { name: 'Яблоки', name_en: 'apple, raw', grams: 400, display_text: '4 шт.', is_optional: false },
      { name: 'Мука', name_en: 'wheat flour', grams: 100, display_text: '3/4 стакана', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 60, display_text: '60 г', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 80, display_text: '4 ст. л.', is_optional: false },
    ],
    steps: ['Карамелизуйте сахар с маслом, выложите яблоки.', 'Накройте тестом.', 'Запекайте 30 минут и переверните.'],
  },
  {
    title: 'Оджахури',
    description: 'Грузинское жаркое из свинины с картофелем.',
    cuisine: 'georgian', category: 'main', base_servings: 2, time_minutes: 45,
    ingredients: [
      { name: 'Свинина', name_en: 'pork, raw', grams: 300, display_text: '300 г', is_optional: false },
      { name: 'Картофель', name_en: 'potato, raw', grams: 300, display_text: '3 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: ['Обжарьте свинину кусочками.', 'Добавьте жареный картофель и лук.', 'Приправьте зеленью, посолите.'],
  },
  {
    title: 'Пхали из шпината',
    description: 'Грузинская закуска из шпината с орехами.',
    cuisine: 'georgian', category: 'snack', base_servings: 2, time_minutes: 20,
    ingredients: [
      { name: 'Шпинат', name_en: 'spinach, raw', grams: 300, display_text: '300 г', is_optional: false },
      { name: 'Грецкие орехи', name_en: 'walnuts', grams: 60, display_text: '60 г', is_optional: false },
      { name: 'Чеснок', name_en: 'garlic, raw', grams: 10, display_text: '2 зубчика', is_optional: false },
    ],
    steps: ['Припустите шпинат и отожмите.', 'Измельчите с орехами, чесноком и специями.', 'Сформируйте шарики.'],
  },
  {
    title: 'Ягодный смузи',
    description: 'Освежающий смузи с клубникой и бананом.',
    cuisine: 'russian', category: 'drink', base_servings: 2, time_minutes: 5,
    ingredients: [
      { name: 'Клубника', name_en: 'strawberries, raw', grams: 200, display_text: '200 г', is_optional: false },
      { name: 'Банан', name_en: 'banana, raw', grams: 120, display_text: '1 шт.', is_optional: false },
      { name: 'Йогурт', name_en: 'yogurt, plain', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Мёд', name_en: 'honey', grams: 20, display_text: '1 ст. л.', is_optional: false },
    ],
    steps: ['Сложите всё в блендер.', 'Взбейте до однородности.'],
  },
  {
    title: 'Тост с авокадо и яйцом',
    description: 'Модный сытный завтрак.',
    cuisine: 'mediterranean', category: 'breakfast', base_servings: 2, time_minutes: 15,
    ingredients: [
      { name: 'Хлеб', name_en: 'bread, white', grams: 100, display_text: '2 ломтика', is_optional: false },
      { name: 'Авокадо', name_en: 'avocado, raw', grams: 150, display_text: '1 шт.', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 100, display_text: '2 шт.', is_optional: false },
    ],
    steps: ['Подсушите хлеб.', 'Разомните авокадо, посолите, намажьте.', 'Сверху — яйцо пашот или глазунья.'],
  },
  {
    title: 'Чизкейк',
    description: 'Нежный запечённый чизкейк.',
    cuisine: 'french', category: 'dessert', base_servings: 2, time_minutes: 70,
    ingredients: [
      { name: 'Сливочный сыр', name_en: 'cream cheese', grams: 300, display_text: '300 г', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 100, display_text: '2 шт.', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 80, display_text: '4 ст. л.', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 40, display_text: '40 г', is_optional: false },
    ],
    steps: ['Взбейте сливочный сыр с сахаром и яйцами.', 'Вылейте в форму на масляную основу.', 'Запекайте при 160 °C 45 минут.'],
  },
  {
    title: 'Варёная кукуруза',
    description: 'Сладкая кукуруза с маслом.',
    cuisine: 'mediterranean', category: 'side', base_servings: 2, time_minutes: 25,
    ingredients: [
      { name: 'Кукуруза', name_en: 'corn, sweet, raw', grams: 400, display_text: '2 початка', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 20, display_text: '20 г', is_optional: false },
    ],
    steps: ['Отварите початки 15 минут.', 'Натрите маслом и солью.'],
  },
]
