import type { GeneratedRecipe } from '../server/utils/anthropic'

// Рецепты, написанные вручную. КБЖУ НЕ указываем — он считается детерминированно
// из граммовки по справочнику USDA (name_en — каноническое английское название).
// Только калорийные ингредиенты в списке; соль/вода/специи — в шагах (0 ккал и
// не находятся в USDA, иначе рецепт помечается непроверенным).
export const RECIPES: GeneratedRecipe[] = [
  {
    title: 'Овсянка с бананом и мёдом',
    description: 'Тёплый сытный завтрак на молоке.',
    cuisine: 'russian',
    category: 'breakfast',
    base_servings: 2,
    time_minutes: 15,
    ingredients: [
      { name: 'Овсяные хлопья', name_en: 'rolled oats', grams: 100, display_text: '1 стакан', is_optional: false },
      { name: 'Молоко', name_en: 'milk, whole', grams: 300, display_text: '1.5 стакана', is_optional: false },
      { name: 'Банан', name_en: 'banana, raw', grams: 120, display_text: '1 шт.', is_optional: false },
      { name: 'Мёд', name_en: 'honey', grams: 30, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Доведите молоко до кипения, всыпьте хлопья.',
      'Варите 5–7 минут, помешивая, до загустения.',
      'Разложите по тарелкам, добавьте нарезанный банан и полейте мёдом.',
    ],
  },
  {
    title: 'Гречка с курицей и овощами',
    description: 'Классический сытный обед или ужин.',
    cuisine: 'russian',
    category: 'main',
    base_servings: 2,
    time_minutes: 35,
    ingredients: [
      { name: 'Гречневая крупа', name_en: 'buckwheat groats', grams: 150, display_text: '3/4 стакана', is_optional: false },
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 300, display_text: '2 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Подсолнечное масло', name_en: 'sunflower oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Отварите гречку в подсолённой воде до готовности.',
      'Нарежьте курицу кубиками, лук и морковь — мелко.',
      'Обжарьте лук и морковь на масле, добавьте курицу, готовьте 10 минут.',
      'Смешайте с гречкой, посолите и поперчите по вкусу.',
    ],
  },
  {
    title: 'Борщ',
    description: 'Наваристый свекольный суп на говядине.',
    cuisine: 'russian',
    category: 'soup',
    base_servings: 2,
    time_minutes: 90,
    ingredients: [
      { name: 'Говядина', name_en: 'beef, raw', grams: 250, display_text: '250 г', is_optional: false },
      { name: 'Свёкла', name_en: 'beets, raw', grams: 150, display_text: '1 шт.', is_optional: false },
      { name: 'Капуста', name_en: 'cabbage, raw', grams: 150, display_text: '1/4 кочана', is_optional: false },
      { name: 'Картофель', name_en: 'potato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Томатная паста', name_en: 'tomato paste', grams: 40, display_text: '2 ст. л.', is_optional: false },
    ],
    steps: [
      'Сварите бульон из говядины (около часа), достаньте мясо и нарежьте.',
      'Добавьте в бульон картофель и капусту.',
      'Обжарьте лук, морковь и тёртую свёклу с томатной пастой, отправьте в суп.',
      'Верните мясо, варите ещё 10 минут, посолите по вкусу.',
    ],
  },
  {
    title: 'Салат Оливье',
    description: 'Праздничный салат с ветчиной и горошком.',
    cuisine: 'russian',
    category: 'salad',
    base_servings: 2,
    time_minutes: 40,
    ingredients: [
      { name: 'Картофель', name_en: 'potato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 100, display_text: '2 шт.', is_optional: false },
      { name: 'Ветчина', name_en: 'ham, sliced', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Зелёный горошек', name_en: 'peas, green, raw', grams: 100, display_text: '1/2 банки', is_optional: false },
      { name: 'Огурцы', name_en: 'cucumber, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Майонез', name_en: 'mayonnaise', grams: 80, display_text: '4 ст. л.', is_optional: false },
    ],
    steps: [
      'Отварите картофель, морковь и яйца, остудите.',
      'Нарежьте все ингредиенты мелкими кубиками.',
      'Добавьте горошек, заправьте майонезом, посолите по вкусу.',
    ],
  },
  {
    title: 'Спагетти болоньезе',
    description: 'Паста с мясным томатным соусом.',
    cuisine: 'italian',
    category: 'main',
    base_servings: 2,
    time_minutes: 40,
    ingredients: [
      { name: 'Спагетти', name_en: 'pasta, dry', grams: 200, display_text: '200 г', is_optional: false },
      { name: 'Говяжий фарш', name_en: 'ground beef, raw', grams: 250, display_text: '250 г', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 250, display_text: '3 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
      { name: 'Пармезан', name_en: 'parmesan cheese', grams: 30, display_text: '30 г', is_optional: true },
    ],
    steps: [
      'Отварите спагетти аль денте.',
      'Обжарьте лук на оливковом масле, добавьте фарш, обжарьте до румяности.',
      'Добавьте нарезанные томаты, тушите 15 минут, посолите.',
      'Подавайте соус на спагетти, посыпав пармезаном.',
    ],
  },
  {
    title: 'Капрезе',
    description: 'Лёгкий салат с моцареллой и томатами.',
    cuisine: 'italian',
    category: 'salad',
    base_servings: 2,
    time_minutes: 10,
    ingredients: [
      { name: 'Моцарелла', name_en: 'mozzarella cheese', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
      { name: 'Базилик', name_en: 'basil, fresh', grams: 10, display_text: 'несколько листьев', is_optional: false },
    ],
    steps: [
      'Нарежьте томаты и моцареллу кружочками.',
      'Выложите слоями, чередуя с листьями базилика.',
      'Полейте оливковым маслом, посолите по вкусу.',
    ],
  },
  {
    title: 'Карри с нутом',
    description: 'Ароматное вегетарианское карри с рисом.',
    cuisine: 'indian',
    category: 'main',
    base_servings: 2,
    time_minutes: 35,
    ingredients: [
      { name: 'Нут', name_en: 'chickpeas, canned', grams: 250, display_text: '1 банка', is_optional: false },
      { name: 'Кокосовое молоко', name_en: 'coconut milk', grams: 200, display_text: '1 стакан', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 150, display_text: '2 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
      { name: 'Рис басмати', name_en: 'rice, white, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
    ],
    steps: [
      'Отварите рис.',
      'Обжарьте лук на масле, добавьте карри-специи по вкусу.',
      'Добавьте томаты и нут, влейте кокосовое молоко, тушите 15 минут.',
      'Подавайте с рисом.',
    ],
  },
  {
    title: 'Дал из красной чечевицы',
    description: 'Согревающий чечевичный суп-пюре.',
    cuisine: 'indian',
    category: 'soup',
    base_servings: 2,
    time_minutes: 30,
    ingredients: [
      { name: 'Красная чечевица', name_en: 'lentils, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 60, display_text: '1 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 15, display_text: '1 ст. л.', is_optional: false },
    ],
    steps: [
      'Промойте чечевицу, залейте водой и варите 20 минут.',
      'Обжарьте лук и морковь на масле со специями.',
      'Добавьте зажарку к чечевице, посолите, при желании пробейте блендером.',
    ],
  },
  {
    title: 'Бибимбап',
    description: 'Корейская миска риса с говядиной, овощами и яйцом.',
    cuisine: 'korean',
    category: 'main',
    base_servings: 2,
    time_minutes: 40,
    ingredients: [
      { name: 'Рис', name_en: 'rice, white, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
      { name: 'Говядина', name_en: 'beef, raw', grams: 200, display_text: '200 г', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Шпинат', name_en: 'spinach, raw', grams: 80, display_text: '2 горсти', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 100, display_text: '2 шт.', is_optional: false },
      { name: 'Кунжутное масло', name_en: 'sesame oil', grams: 15, display_text: '1 ст. л.', is_optional: false },
    ],
    steps: [
      'Отварите рис. Нарежьте говядину полосками и обжарьте.',
      'Припустите морковь и шпинат по отдельности на кунжутном масле.',
      'Пожарьте яичницу-глазунью.',
      'Соберите миску: рис, сверху овощи, мясо и яйцо.',
    ],
  },
  {
    title: 'Корейская морковь',
    description: 'Острая маринованная морковь по-корейски.',
    cuisine: 'korean',
    category: 'salad',
    base_servings: 2,
    time_minutes: 20,
    ingredients: [
      { name: 'Морковь', name_en: 'carrot, raw', grams: 300, display_text: '3 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 30, display_text: '2 ст. л.', is_optional: false },
      { name: 'Чеснок', name_en: 'garlic, raw', grams: 15, display_text: '3 зубчика', is_optional: false },
    ],
    steps: [
      'Натрите морковь на тёрке для корейской моркови.',
      'Добавьте измельчённый чеснок, соль и специи по вкусу.',
      'Раскалите масло и полейте морковь, перемешайте, дайте настояться час.',
    ],
  },
  {
    title: 'Шакшука',
    description: 'Яйца, запечённые в томатном соусе.',
    cuisine: 'mediterranean',
    category: 'breakfast',
    base_servings: 2,
    time_minutes: 25,
    ingredients: [
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 200, display_text: '4 шт.', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 300, display_text: '4 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Болгарский перец', name_en: 'bell pepper, raw', grams: 120, display_text: '1 шт.', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Обжарьте лук и перец на оливковом масле.',
      'Добавьте нарезанные томаты, тушите до густоты соуса, посолите.',
      'Сделайте углубления, вбейте яйца и готовьте под крышкой до схватывания белка.',
    ],
  },
  {
    title: 'Греческий салат',
    description: 'Свежий салат с фетой и оливками.',
    cuisine: 'mediterranean',
    category: 'salad',
    base_servings: 2,
    time_minutes: 15,
    ingredients: [
      { name: 'Томаты', name_en: 'tomato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Огурцы', name_en: 'cucumber, raw', grams: 150, display_text: '1 шт.', is_optional: false },
      { name: 'Фета', name_en: 'feta cheese', grams: 100, display_text: '100 г', is_optional: false },
      { name: 'Оливки', name_en: 'olives', grams: 50, display_text: '50 г', is_optional: false },
      { name: 'Болгарский перец', name_en: 'bell pepper, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Нарежьте овощи крупными кусками.',
      'Добавьте оливки и фету, нарезанную кубиками.',
      'Полейте оливковым маслом, посолите и приправьте орегано.',
    ],
  },
  {
    title: 'Пад тай с креветками',
    description: 'Тайская рисовая лапша с креветками и арахисом.',
    cuisine: 'thai',
    category: 'main',
    base_servings: 2,
    time_minutes: 30,
    ingredients: [
      { name: 'Рисовая лапша', name_en: 'rice noodles, dry', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Креветки', name_en: 'shrimp, raw', grams: 200, display_text: '200 г', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 100, display_text: '2 шт.', is_optional: false },
      { name: 'Арахис', name_en: 'peanuts', grams: 40, display_text: '40 г', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 60, display_text: '1 шт.', is_optional: false },
    ],
    steps: [
      'Замочите лапшу в горячей воде до мягкости.',
      'Обжарьте креветки и тёртую морковь на масле, отодвиньте, вбейте яйца и размешайте.',
      'Добавьте лапшу и соус (рыбный, тамаринд по вкусу), прогрейте.',
      'Подавайте, посыпав рублёным арахисом.',
    ],
  },
  {
    title: 'Сырники',
    description: 'Творожные оладьи на завтрак.',
    cuisine: 'russian',
    category: 'breakfast',
    base_servings: 2,
    time_minutes: 25,
    ingredients: [
      { name: 'Творог', name_en: 'cottage cheese', grams: 300, display_text: '300 г', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 50, display_text: '1 шт.', is_optional: false },
      { name: 'Мука', name_en: 'wheat flour', grams: 60, display_text: '4 ст. л.', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 30, display_text: '1.5 ст. л.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 20, display_text: 'для жарки', is_optional: false },
    ],
    steps: [
      'Разомните творог с яйцом, сахаром и мукой.',
      'Сформируйте небольшие шайбы, обваляйте в муке.',
      'Обжарьте на масле с двух сторон до румяной корочки.',
    ],
  },
  {
    title: 'Блинчики',
    description: 'Тонкие блины на молоке.',
    cuisine: 'french',
    category: 'dessert',
    base_servings: 2,
    time_minutes: 30,
    ingredients: [
      { name: 'Мука', name_en: 'wheat flour', grams: 150, display_text: '1 стакан', is_optional: false },
      { name: 'Молоко', name_en: 'milk, whole', grams: 250, display_text: '1.25 стакана', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 100, display_text: '2 шт.', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 40, display_text: '2 ст. л.', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter', grams: 30, display_text: '30 г', is_optional: false },
    ],
    steps: [
      'Смешайте муку, яйца, сахар и молоко в однородное тесто.',
      'Добавьте растопленное масло.',
      'Выпекайте тонкие блины на разогретой сковороде с двух сторон.',
    ],
  },
  {
    title: 'Мисо-суп с тофу',
    description: 'Лёгкий японский суп.',
    cuisine: 'japanese',
    category: 'soup',
    base_servings: 2,
    time_minutes: 15,
    ingredients: [
      { name: 'Тофу', name_en: 'tofu, firm', grams: 150, display_text: '150 г', is_optional: false },
      { name: 'Мисо паста', name_en: 'miso', grams: 40, display_text: '2 ст. л.', is_optional: false },
      { name: 'Водоросли вакаме', name_en: 'seaweed, wakame, raw', grams: 20, display_text: '20 г', is_optional: false },
      { name: 'Зелёный лук', name_en: 'scallions, raw', grams: 20, display_text: '2 пера', is_optional: false },
    ],
    steps: [
      'Доведите воду (около 700 мл) до кипения, замочите вакаме.',
      'Снимите с сильного огня, растворите мисо-пасту (не кипятить).',
      'Добавьте кубики тофу и нарезанный зелёный лук.',
    ],
  },
]
