import type { GeneratedRecipe } from '../server/utils/anthropic'

// Второй батч рецептов. Те же правила: только калорийные ингредиенты,
// name_en — каноническое английское название для USDA.
export const RECIPES_2: GeneratedRecipe[] = [
  {
    title: 'Куриный суп с лапшой',
    description: 'Лёгкий домашний суп на курином бульоне.',
    cuisine: 'russian',
    category: 'soup',
    base_servings: 2,
    time_minutes: 40,
    ingredients: [
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 250, display_text: '2 шт.', is_optional: false },
      { name: 'Яичная лапша', name_en: 'egg noodles, dry', grams: 80, display_text: '80 г', is_optional: false },
      { name: 'Картофель', name_en: 'potato, raw', grams: 150, display_text: '1–2 шт.', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 70, display_text: '1 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 70, display_text: '1 шт.', is_optional: false },
    ],
    steps: [
      'Сварите курицу, выньте и нарежьте.',
      'В бульон добавьте картофель и морковь, варите 10 минут.',
      'Добавьте лапшу и обжаренный лук, верните мясо, варите 5 минут.',
    ],
  },
  {
    title: 'Винегрет',
    description: 'Постный овощной салат со свёклой.',
    cuisine: 'russian',
    category: 'salad',
    base_servings: 2,
    time_minutes: 30,
    ingredients: [
      { name: 'Свёкла', name_en: 'beets, raw', grams: 150, display_text: '1 шт.', is_optional: false },
      { name: 'Картофель', name_en: 'potato, raw', grams: 150, display_text: '2 шт.', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Зелёный горошек', name_en: 'peas, green, raw', grams: 80, display_text: '80 г', is_optional: false },
      { name: 'Огурцы', name_en: 'cucumber, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Подсолнечное масло', name_en: 'sunflower oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Отварите свёклу, картофель и морковь, остудите и нарежьте кубиками.',
      'Добавьте нарезанные огурцы и горошек.',
      'Заправьте маслом, посолите по вкусу.',
    ],
  },
  {
    title: 'Плов с говядиной',
    description: 'Рассыпчатый рис с мясом и морковью.',
    cuisine: 'russian',
    category: 'main',
    base_servings: 2,
    time_minutes: 70,
    ingredients: [
      { name: 'Рис', name_en: 'rice, white, raw', grams: 200, display_text: '1 стакан', is_optional: false },
      { name: 'Говядина', name_en: 'beef, raw', grams: 250, display_text: '250 г', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 150, display_text: '2 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 30, display_text: '2 ст. л.', is_optional: false },
    ],
    steps: [
      'Обжарьте мясо на масле, добавьте лук и морковь соломкой.',
      'Всыпьте рис, залейте водой на 2 см выше риса, посолите.',
      'Готовьте под крышкой на слабом огне до впитывания воды.',
    ],
  },
  {
    title: 'Творожная запеканка',
    description: 'Нежная запеканка из творога к чаю.',
    cuisine: 'russian',
    category: 'dessert',
    base_servings: 2,
    time_minutes: 50,
    ingredients: [
      { name: 'Творог', name_en: 'cottage cheese', grams: 400, display_text: '400 г', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 100, display_text: '2 шт.', is_optional: false },
      { name: 'Манная крупа', name_en: 'semolina', grams: 50, display_text: '3 ст. л.', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 40, display_text: '2 ст. л.', is_optional: false },
      { name: 'Изюм', name_en: 'raisins', grams: 40, display_text: '40 г', is_optional: true },
    ],
    steps: [
      'Смешайте творог, яйца, манку и сахар, добавьте изюм.',
      'Выложите в форму, разровняйте.',
      'Запекайте при 180 °C около 35 минут до румяной корочки.',
    ],
  },
  {
    title: 'Картофельное пюре',
    description: 'Классический гарнир на молоке и масле.',
    cuisine: 'russian',
    category: 'side',
    base_servings: 2,
    time_minutes: 30,
    ingredients: [
      { name: 'Картофель', name_en: 'potato, raw', grams: 500, display_text: '5 шт.', is_optional: false },
      { name: 'Молоко', name_en: 'milk, 3.25% milkfat', grams: 120, display_text: '1/2 стакана', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 40, display_text: '40 г', is_optional: false },
    ],
    steps: [
      'Отварите картофель в подсолённой воде до мягкости.',
      'Слейте воду, добавьте тёплое молоко и масло.',
      'Разомните до однородности.',
    ],
  },
  {
    title: 'Шарлотка с яблоками',
    description: 'Простой бисквитный пирог с яблоками.',
    cuisine: 'russian',
    category: 'dessert',
    base_servings: 2,
    time_minutes: 50,
    ingredients: [
      { name: 'Яблоки', name_en: 'apple, raw', grams: 300, display_text: '3 шт.', is_optional: false },
      { name: 'Мука', name_en: 'wheat flour', grams: 120, display_text: '1 стакан', is_optional: false },
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 150, display_text: '3 шт.', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 120, display_text: '1 стакан', is_optional: false },
    ],
    steps: [
      'Взбейте яйца с сахаром, добавьте муку.',
      'Выложите нарезанные яблоки в форму, залейте тестом.',
      'Выпекайте при 180 °C около 35 минут.',
    ],
  },
  {
    title: 'Ризотто с грибами',
    description: 'Кремовое рисовое ризотто с грибами.',
    cuisine: 'italian',
    category: 'main',
    base_servings: 2,
    time_minutes: 40,
    ingredients: [
      { name: 'Рис', name_en: 'rice, white, raw', grams: 180, display_text: '1 стакан', is_optional: false },
      { name: 'Грибы', name_en: 'mushrooms, white, raw', grams: 200, display_text: '200 г', is_optional: false },
      { name: 'Пармезан', name_en: 'parmesan cheese', grams: 40, display_text: '40 г', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 30, display_text: '30 г', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
    ],
    steps: [
      'Обжарьте лук и грибы на масле.',
      'Добавьте рис, постепенно вливайте горячий бульон, помешивая.',
      'Когда рис готов, вмешайте пармезан, посолите.',
    ],
  },
  {
    title: 'Минестроне',
    description: 'Густой итальянский овощной суп.',
    cuisine: 'italian',
    category: 'soup',
    base_servings: 2,
    time_minutes: 40,
    ingredients: [
      { name: 'Белая фасоль', name_en: 'beans, white, canned', grams: 200, display_text: '1 банка', is_optional: false },
      { name: 'Морковь', name_en: 'carrot, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Сельдерей', name_en: 'celery, raw', grams: 80, display_text: '2 стебля', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 150, display_text: '2 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 70, display_text: '1 шт.', is_optional: false },
      { name: 'Паста', name_en: 'pasta, dry', grams: 60, display_text: '60 г', is_optional: false },
    ],
    steps: [
      'Обжарьте лук, морковь и сельдерей.',
      'Добавьте томаты, воду и фасоль, варите 15 минут.',
      'Всыпьте пасту, варите до готовности, посолите.',
    ],
  },
  {
    title: 'Брускетта с томатами',
    description: 'Хрустящие тосты с томатами и чесноком.',
    cuisine: 'italian',
    category: 'snack',
    base_servings: 2,
    time_minutes: 15,
    ingredients: [
      { name: 'Хлеб', name_en: 'bread, white', grams: 150, display_text: '4 ломтика', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 20, display_text: '1.5 ст. л.', is_optional: false },
      { name: 'Чеснок', name_en: 'garlic, raw', grams: 10, display_text: '2 зубчика', is_optional: false },
    ],
    steps: [
      'Подсушите хлеб и натрите чесноком.',
      'Выложите нарезанные томаты, сбрызните маслом, посолите.',
    ],
  },
  {
    title: 'Карри с курицей',
    description: 'Индийское карри в сливочно-томатном соусе.',
    cuisine: 'indian',
    category: 'main',
    base_servings: 2,
    time_minutes: 40,
    ingredients: [
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 300, display_text: '2 шт.', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Йогурт', name_en: 'yogurt, plain', grams: 100, display_text: '100 г', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 20, display_text: '20 г', is_optional: false },
      { name: 'Рис', name_en: 'rice, white, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
    ],
    steps: [
      'Обжарьте лук на масле со специями карри.',
      'Добавьте курицу и томаты, тушите 15 минут, вмешайте йогурт.',
      'Подавайте с отварным рисом.',
    ],
  },
  {
    title: 'Алу гоби',
    description: 'Индийское рагу из картофеля и цветной капусты.',
    cuisine: 'indian',
    category: 'side',
    base_servings: 2,
    time_minutes: 35,
    ingredients: [
      { name: 'Картофель', name_en: 'potato, raw', grams: 250, display_text: '2–3 шт.', is_optional: false },
      { name: 'Цветная капуста', name_en: 'cauliflower, raw', grams: 300, display_text: '1/2 кочана', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 25, display_text: '2 ст. л.', is_optional: false },
    ],
    steps: [
      'Обжарьте лук со специями (куркума, кумин).',
      'Добавьте картофель и капусту, немного воды.',
      'Тушите под крышкой до мягкости, посолите.',
    ],
  },
  {
    title: 'Омлет с сыром',
    description: 'Пышный омлет на завтрак.',
    cuisine: 'french',
    category: 'breakfast',
    base_servings: 2,
    time_minutes: 15,
    ingredients: [
      { name: 'Яйца', name_en: 'egg, whole, raw', grams: 200, display_text: '4 шт.', is_optional: false },
      { name: 'Молоко', name_en: 'milk, 3.25% milkfat', grams: 60, display_text: '4 ст. л.', is_optional: false },
      { name: 'Сыр чеддер', name_en: 'cheddar cheese', grams: 60, display_text: '60 г', is_optional: false },
      { name: 'Сливочное масло', name_en: 'butter, salted', grams: 15, display_text: '15 г', is_optional: false },
    ],
    steps: [
      'Взбейте яйца с молоком и солью.',
      'Вылейте на сковороду с маслом, посыпьте тёртым сыром.',
      'Готовьте под крышкой до схватывания.',
    ],
  },
  {
    title: 'Рататуй',
    description: 'Прованское овощное рагу.',
    cuisine: 'french',
    category: 'side',
    base_servings: 2,
    time_minutes: 45,
    ingredients: [
      { name: 'Баклажан', name_en: 'eggplant, raw', grams: 200, display_text: '1 шт.', is_optional: false },
      { name: 'Кабачок', name_en: 'zucchini, raw', grams: 200, display_text: '1 шт.', is_optional: false },
      { name: 'Болгарский перец', name_en: 'bell pepper, raw', grams: 120, display_text: '1 шт.', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Оливковое масло', name_en: 'olive oil', grams: 25, display_text: '2 ст. л.', is_optional: false },
    ],
    steps: [
      'Нарежьте все овощи кубиками.',
      'Обжарьте лук и перец, добавьте баклажан и кабачок.',
      'Добавьте томаты, тушите 20 минут, посолите.',
    ],
  },
  {
    title: 'Чили кон карне',
    description: 'Острое рагу с фаршем и фасолью.',
    cuisine: 'mexican',
    category: 'main',
    base_servings: 2,
    time_minutes: 40,
    ingredients: [
      { name: 'Говяжий фарш', name_en: 'ground beef, raw', grams: 250, display_text: '250 г', is_optional: false },
      { name: 'Красная фасоль', name_en: 'beans, kidney, canned', grams: 200, display_text: '1 банка', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 200, display_text: '2 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 80, display_text: '1 шт.', is_optional: false },
      { name: 'Болгарский перец', name_en: 'bell pepper, raw', grams: 120, display_text: '1 шт.', is_optional: false },
    ],
    steps: [
      'Обжарьте лук и перец, добавьте фарш.',
      'Добавьте томаты и специи (паприка, чили), тушите 15 минут.',
      'Всыпьте фасоль, прогрейте, посолите.',
    ],
  },
  {
    title: 'Кесадилья с курицей',
    description: 'Тортилья с курицей и расплавленным сыром.',
    cuisine: 'mexican',
    category: 'main',
    base_servings: 2,
    time_minutes: 25,
    ingredients: [
      { name: 'Тортилья', name_en: 'tortilla, flour', grams: 160, display_text: '4 шт.', is_optional: false },
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 200, display_text: '1 шт.', is_optional: false },
      { name: 'Сыр чеддер', name_en: 'cheddar cheese', grams: 120, display_text: '120 г', is_optional: false },
      { name: 'Болгарский перец', name_en: 'bell pepper, raw', grams: 100, display_text: '1 шт.', is_optional: false },
    ],
    steps: [
      'Обжарьте нарезанную курицу и перец.',
      'На тортилью выложите начинку и сыр, накройте второй.',
      'Обжарьте с двух сторон до расплавления сыра.',
    ],
  },
  {
    title: 'Гуакамоле',
    description: 'Соус-дип из авокадо.',
    cuisine: 'mexican',
    category: 'snack',
    base_servings: 2,
    time_minutes: 10,
    ingredients: [
      { name: 'Авокадо', name_en: 'avocado, raw', grams: 200, display_text: '1 шт.', is_optional: false },
      { name: 'Томаты', name_en: 'tomato, raw', grams: 100, display_text: '1 шт.', is_optional: false },
      { name: 'Лук', name_en: 'onion, raw', grams: 40, display_text: '1/2 шт.', is_optional: false },
    ],
    steps: [
      'Разомните мякоть авокадо вилкой.',
      'Добавьте мелко нарезанные томаты и лук, посолите.',
    ],
  },
  {
    title: 'Зелёное карри с курицей',
    description: 'Тайское карри на кокосовом молоке.',
    cuisine: 'thai',
    category: 'main',
    base_servings: 2,
    time_minutes: 35,
    ingredients: [
      { name: 'Куриное филе', name_en: 'chicken breast, raw', grams: 300, display_text: '2 шт.', is_optional: false },
      { name: 'Кокосовое молоко', name_en: 'coconut milk, canned', grams: 200, display_text: '1 стакан', is_optional: false },
      { name: 'Болгарский перец', name_en: 'bell pepper, raw', grams: 120, display_text: '1 шт.', is_optional: false },
      { name: 'Рис', name_en: 'rice, white, raw', grams: 150, display_text: '3/4 стакана', is_optional: false },
      { name: 'Растительное масло', name_en: 'vegetable oil', grams: 15, display_text: '1 ст. л.', is_optional: false },
    ],
    steps: [
      'Обжарьте курицу с пастой зелёного карри.',
      'Влейте кокосовое молоко, добавьте перец, тушите 15 минут.',
      'Подавайте с рисом.',
    ],
  },
  {
    title: 'Греческий йогурт с орехами и мёдом',
    description: 'Быстрый белковый завтрак.',
    cuisine: 'mediterranean',
    category: 'breakfast',
    base_servings: 2,
    time_minutes: 5,
    ingredients: [
      { name: 'Греческий йогурт', name_en: 'yogurt, greek, plain', grams: 300, display_text: '300 г', is_optional: false },
      { name: 'Грецкие орехи', name_en: 'walnuts', grams: 40, display_text: '40 г', is_optional: false },
      { name: 'Мёд', name_en: 'honey', grams: 30, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Разложите йогурт по пиалам.',
      'Посыпьте рублёными орехами и полейте мёдом.',
    ],
  },
  {
    title: 'Какао на молоке',
    description: 'Тёплый шоколадный напиток.',
    cuisine: 'russian',
    category: 'drink',
    base_servings: 2,
    time_minutes: 10,
    ingredients: [
      { name: 'Молоко', name_en: 'milk, 3.25% milkfat', grams: 500, display_text: '2.5 стакана', is_optional: false },
      { name: 'Какао-порошок', name_en: 'cocoa, dry powder, unsweetened', grams: 20, display_text: '2 ст. л.', is_optional: false },
      { name: 'Сахар', name_en: 'sugar', grams: 30, display_text: '1.5 ст. л.', is_optional: false },
    ],
    steps: [
      'Смешайте какао с сахаром, разведите небольшим количеством молока.',
      'Влейте остальное молоко, прогрейте до горячего, помешивая.',
    ],
  },
]
